version: "3"
services:
  app:
    build:
      args:
        user: nbc_transactions
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: research
    container_name: nbctransaction-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - userauth

  db:
    image: mysql:5.7
    container_name: process-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - userauth

  nginx:
    image: nginx:alpine
    container_name: userauth-nginx
    restart: unless-stopped
    ports:
      - 8022:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - nbc_transactions

networks:
  userauth:
    driver: bridge
    
volumes:
  dbdata:
    driver: local

